package com.mockapilab.modules.ai.validation;

import com.mockapilab.modules.ai.model.candidate.AiCandidateContract;
import com.mockapilab.modules.ai.model.candidate.AiCandidateEndpoint;
import com.mockapilab.modules.ai.model.candidate.AiCandidateParameter;
import com.mockapilab.modules.ai.model.candidate.AiCandidateRequestBody;
import com.mockapilab.modules.ai.model.candidate.AiCandidateResponse;
import com.mockapilab.modules.ai.model.candidate.AiCandidateSchema;
import com.mockapilab.modules.contract.validation.ContractValidationException;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Deterministic validator for candidate API contracts generated by AI extraction.
 * Rejects invalid, hallucinated, or structurally malformed candidate contracts.
 */
@Component
public class AiCandidateValidator {

    private static final Set<String> ALLOWED_METHODS = Set.of("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD");
    private static final Set<String> ALLOWED_TYPES = Set.of("string", "integer", "number", "boolean", "array", "object");
    private static final Set<String> ALLOWED_PARAM_LOCATIONS = Set.of("path", "query", "header", "cookie");
    private static final Pattern PATH_PARAM_PATTERN = Pattern.compile("\\{([^}]+)\\}");

    public void validate(AiCandidateContract candidate) {
        if (candidate == null) {
            throw new ContractValidationException("AI extraction failed to produce a valid candidate contract");
        }

        if (candidate.endpoints() == null || candidate.endpoints().isEmpty()) {
            throw new ContractValidationException("Candidate contract must contain at least one endpoint");
        }

        Set<String> definedSchemas = candidate.schemas() != null ? candidate.schemas().keySet() : Set.of();

        // 1. Validate Schemas first
        if (candidate.schemas() != null) {
            candidate.schemas().forEach((name, schema) -> {
                if (!StringUtils.hasText(name)) {
                    throw new ContractValidationException("Schema definition name cannot be blank");
                }
                validateSchema(schema, "Schema '" + name + "'", definedSchemas);
            });
        }

        // 2. Validate Endpoints
        Set<String> endpointKeys = new HashSet<>();
        for (AiCandidateEndpoint endpoint : candidate.endpoints()) {
            validateEndpoint(endpoint, endpointKeys, definedSchemas);
        }
    }

    private void validateEndpoint(AiCandidateEndpoint endpoint, Set<String> endpointKeys, Set<String> definedSchemas) {
        if (endpoint == null) {
            throw new ContractValidationException("Endpoint definition cannot be null");
        }

        if (!StringUtils.hasText(endpoint.path())) {
            throw new ContractValidationException("Endpoint path cannot be empty");
        }

        String path = endpoint.path().trim();
        if (!path.startsWith("/")) {
            throw new ContractValidationException("Endpoint path must start with a leading slash '/': " + path);
        }

        if (!StringUtils.hasText(endpoint.method())) {
            throw new ContractValidationException("Endpoint HTTP method cannot be empty for path: " + path);
        }

        String method = endpoint.method().trim().toUpperCase();
        if (!ALLOWED_METHODS.contains(method)) {
            throw new ContractValidationException("Unsupported HTTP method '" + method + "' for path: " + path);
        }

        String endpointKey = method + " " + path;
        if (!endpointKeys.add(endpointKey)) {
            throw new ContractValidationException("Duplicate endpoint definition found: " + endpointKey);
        }

        // Extract path variables from URL template
        Set<String> pathVariablesInUrl = new HashSet<>();
        Matcher matcher = PATH_PARAM_PATTERN.matcher(path);
        while (matcher.find()) {
            pathVariablesInUrl.add(matcher.group(1));
        }

        // Validate Parameters
        if (endpoint.parameters() != null) {
            for (AiCandidateParameter param : endpoint.parameters()) {
                validateParameter(param, endpointKey, pathVariablesInUrl, definedSchemas);
            }
        }

        // Validate Request Body
        if (endpoint.requestBody() != null) {
            validateRequestBody(endpoint.requestBody(), endpointKey, definedSchemas);
        }

        // Validate Responses
        if (endpoint.responses() == null || endpoint.responses().isEmpty()) {
            throw new ContractValidationException("Endpoint " + endpointKey + " must define at least one HTTP response");
        }

        for (AiCandidateResponse response : endpoint.responses()) {
            validateResponse(response, endpointKey, definedSchemas);
        }
    }

    private void validateParameter(AiCandidateParameter param, String endpointKey, Set<String> pathVariablesInUrl, Set<String> definedSchemas) {
        if (param == null || !StringUtils.hasText(param.name())) {
            throw new ContractValidationException("Parameter name cannot be empty for endpoint: " + endpointKey);
        }

        String location = param.in() != null ? param.in().trim().toLowerCase() : "query";
        if (!ALLOWED_PARAM_LOCATIONS.contains(location)) {
            throw new ContractValidationException("Invalid parameter location '" + param.in() + "' for parameter '" + param.name() + "' in endpoint: " + endpointKey);
        }

        if ("path".equalsIgnoreCase(location)) {
            if (!Boolean.TRUE.equals(param.required())) {
                throw new ContractValidationException("Path parameter '" + param.name() + "' must be marked as required in endpoint: " + endpointKey);
            }
            if (!pathVariablesInUrl.contains(param.name())) {
                throw new ContractValidationException("Path parameter '" + param.name() + "' declared in parameters list is missing from path template: " + endpointKey);
            }
        }

        if (param.schema() != null) {
            validateSchema(param.schema(), "Parameter '" + param.name() + "' in endpoint " + endpointKey, definedSchemas);
        }
    }

    private void validateRequestBody(AiCandidateRequestBody requestBody, String endpointKey, Set<String> definedSchemas) {
        if (requestBody.schema() != null) {
            validateSchema(requestBody.schema(), "Request body in endpoint " + endpointKey, definedSchemas);
        }
    }

    private void validateResponse(AiCandidateResponse response, String endpointKey, Set<String> definedSchemas) {
        if (response == null || !StringUtils.hasText(response.statusCode())) {
            throw new ContractValidationException("Response status code cannot be empty in endpoint: " + endpointKey);
        }

        String code = response.statusCode().trim();
        if (!"default".equalsIgnoreCase(code) && !isValidStatusCode(code)) {
            throw new ContractValidationException("Invalid HTTP response status code '" + code + "' in endpoint: " + endpointKey);
        }

        if (response.schema() != null) {
            validateSchema(response.schema(), "Response " + code + " in endpoint " + endpointKey, definedSchemas);
        }
    }

    private boolean isValidStatusCode(String code) {
        try {
            int num = Integer.parseInt(code);
            return num >= 100 && num <= 599;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void validateSchema(AiCandidateSchema schema, String context, Set<String> definedSchemas) {
        if (schema == null) {
            return;
        }

        if (StringUtils.hasText(schema.ref())) {
            String refName = normalizeRefName(schema.ref());
            if (!definedSchemas.contains(refName)) {
                throw new ContractValidationException(context + " references undefined schema: " + schema.ref());
            }
            return;
        }

        if (StringUtils.hasText(schema.type())) {
            String type = schema.type().trim().toLowerCase();
            if (!ALLOWED_TYPES.contains(type)) {
                throw new ContractValidationException(context + " has unsupported schema type: " + schema.type());
            }

            if ("array".equals(type) && schema.items() != null) {
                validateSchema(schema.items(), context + " -> items", definedSchemas);
            }

            if ("object".equals(type) && schema.properties() != null) {
                Map<String, AiCandidateSchema> props = schema.properties();
                props.forEach((propName, propSchema) -> {
                    if (!StringUtils.hasText(propName)) {
                        throw new ContractValidationException(context + " contains blank property name");
                    }
                    validateSchema(propSchema, context + " -> property '" + propName + "'", definedSchemas);
                });

                if (schema.requiredProperties() != null) {
                    for (String req : schema.requiredProperties()) {
                        if (!props.containsKey(req)) {
                            throw new ContractValidationException(context + " lists required property '" + req + "' which is missing from defined properties");
                        }
                    }
                }
            }
        }

        if (schema.enumConstants() != null) {
            if (schema.enumConstants().isEmpty()) {
                throw new ContractValidationException(context + " contains empty enum constants list");
            }
            for (String enumVal : schema.enumConstants()) {
                if (!StringUtils.hasText(enumVal)) {
                    throw new ContractValidationException(context + " contains blank enum value");
                }
            }
        }
    }

    private String normalizeRefName(String ref) {
        if (ref == null) return null;
        if (ref.startsWith("#/components/schemas/")) {
            return ref.substring("#/components/schemas/".length());
        }
        int lastSlash = ref.lastIndexOf('/');
        return lastSlash >= 0 ? ref.substring(lastSlash + 1) : ref;
    }
}